name: FastAPI CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run tests
      run: |
        

    - name: Build Docker image
      run: |
        docker build -t python-app .

    - name: Run tests inside Docker container
      run: |
        docker run --rm -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} python-app pytest
